
[app]
8itempregare.url_base="https://8it.empregare.com"
8itempregare.url_listagem="https://8it.empregare.com/api/pt-br/vagas/buscar?Pag={page}&q=&empresa=QdOcUw7QEYA%7C&hotSiteUrl=8it&carregarFiltro=true&carregarLista=true"
8itempregare.pagina_inicial=1
8itempregare.parar_apos_x_vagas=100

trampos.url_base="https://trampos.co/oportunidades"
trampos.url_listagem="https://trampos.co/api/v2/opportunities?lc=&tr=desenvolvedor&page={page}"
trampos.pagina_inicial=1
trampos.parar_apos_x_vagas=100

programathor.url_base="https://programathor.com.br"
programathor.url_listagem="https://programathor.com.br/jobs/page/{page}"
programathor.pagina_inicial=1
programathor.parar_apos_x_vagas=100

geekhunter.url_base="https://www.geekhunter.com.br"
geekhunter.url_listagem="https://www.geekhunter.com.br/vagas?page={page}"
geekhunter.pagina_inicial=1
geekhunter.parar_apos_x_vagas=100