class Vaga:
    id = "N/A"
    url = "N/A"
    data_scraping = "N/A"
    data_publicacao = "N/A"
    titulo = "N/A"
    empresa = "N/A"
    local_trabalho = "N/A"
    descricao = "N/A"
    responsabilidades = "N/A"
    requisitos = "N/A"
    #requisitos_basicos = "N/A"
    #requisitos_diferenciais = "N/A"
    salario = "N/A"
    beneficios = "N/A"