class Vaga:
    id = "N/A"
    url = "N/A"
    data_scraping = "N/A"
    data_publicacao = "N/A"
    titulo = "N/A"
    empresa = "N/A"
    local_trabalho = "N/A"
    responsabilidades = "N/A"
    requisitos = "N/A"
    salario = "N/A"
    modelo_contratacao = "N/A"
    beneficios = "N/A"